### ISSUE TITLE
add colors for documentation

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/branding#1]
Add the colors from the User Guide/ docs CSS to the STYLE_GUIDE.md

**Comment by orbeckst** [comment]
@lilyminium do you have the colors of your User Guide theme at hand?

**Comment by lilyminium** [comment]
Yup, they should be variations on:

```
/* MDAnalysis orange: #FF9200 */
/* MDAnalysis gray: #808080 */
/* MDAnalysis white: #FFFFFF */
/* MDAnalysis black: #000000 */
/* Very light orange: #FFEBD0 */
/* Code orange: #ca6500 */
/* RTD dark grey: #343131 */
/* RTD light grey: #e6e6e6 */
```

The CSS theme (https://github.com/MDAnalysis/UserGuide/blob/develop/doc/source/_static/custom.css) has some others for coloured elements, where we needed to differentiate between notes, warnings, etc. -- they have some pastel red/orange/yellows (backgrounds) and darker red/orange/yellows (text).
